name: first_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+6

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  flutter_rating_bar: ^4.0.0

  # Firebase 2.x stack (nanopb 2.x)
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.7.7

  # Maps/geo/etc.
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.1

  # UI + misc
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.5.0
  provider: ^6.1.1
  timeago: ^3.6.0
  image_picker: ^1.1.2
  google_fonts: ^6.2.1

  # ML Kit — keep BOTH on 0.12.x to stay on nanopb 2.x
  google_mlkit_translation: ^0.12.0
  google_mlkit_language_id: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
