name: nyari
description: A lifestyle & local discovery app built with Flutter + Firebase
publish_to: "none"

version: 1.0.0+123

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- Firebase (updated to iOS 11+ compatible versions) ---
  firebase_core: 4.1.1
  cloud_firestore: 6.0.2
  firebase_auth: 6.1.0
  firebase_storage: 13.0.2

  # --- Maps & Location ---
  google_maps_flutter: ^2.12.3
  geolocator: ^11.1.0
  geocoding: ^3.0.0

  # --- UI / State ---
  provider: ^6.1.2
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8

  # --- Required by imports in your code ---
  google_fonts: ^6.2.1
  timeago: ^3.6.1
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  google_mlkit_language_id: ^0.13.0
  google_mlkit_translation: ^0.13.0
  firebase_crashlytics: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/nyari_wordmark.png
