name: first_flutter_app
description: Nyari mobile app
publish_to: "none"

version: 1.0.0+9  # bump build number on each upload

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State / UI (add your libs here if you have them)
  cupertino_icons: ^1.0.8

  # --- Firebase / FlutterFire (Xcode 16 compatible) ---
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2

  # --- Location / Geocoding ---
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # --- ML Kit (if you use it) ---
  google_mlkit_commons: ^0.11.0
  google_mlkit_language_id: ^0.13.0
  google_mlkit_translation: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0  # keep at least a sane version

flutter:
  uses-material-design: true

  # If you have assets, list them here
  # assets:
  #   - assets/images/
  #   - assets/icons/
